version: "3.9"
services:
  mmtalent:
    build: .
    ports:
      - "127.0.0.1:8787:8787"
    volumes:
      - ./mmtalent.Rproj:/home/rstudio/mmtalent.Rproj
      - ./renv/activate.R:/home/rstudio/renv/activate.R
      - ./renv/settings.dcf:/home/rstudio/renv/settings.dcf
      - ./renv.lock:/home/rstudio/renv.lock
      - ./_targets.R:/home/rstudio/_targets.R
      - ./R:/home/rstudio/R
      - ./raw-data:/home/rstudio/raw-data
      - ./data:/home/rstudio/data
      - ./tables:/home/rstudio/tables
      - ./figures:/home/rstudio/figures
      - ./reports:/home/rstudio/reports
    environment:
      - "DISABLE_AUTH=true"
